insert into CorAnimal values (1, 'Marron');
insert into CorAnimal values (2, 'Preto');
insert into CorAnimal values (3, 'Branco');
insert into CorAnimal values (4, 'Cinza');
insert into CorAnimal values (5, 'Dourado');
insert into CorAnimal values (6, 'Amarelo');



insert into EspecieAnimal values (1, 'Cachorro');
insert into EspecieAnimal values (2, 'Gato');

 insert into RacaAnimal values (1  ,'Afghan Hound', 1);
 insert into RacaAnimal values (2  ,'Airedale Terrier', 1);
 insert into RacaAnimal values (3  ,'Akita Americano', 1);
 insert into RacaAnimal values (4  ,'Akita Inu', 1);
 insert into RacaAnimal values (5  ,'American Pitbull', 1);
 insert into RacaAnimal values (6  ,'Basset Hound', 1);
 insert into RacaAnimal values (7  ,'Beagle', 1);
 insert into RacaAnimal values (8  ,'Bichon Frisé', 1);
 insert into RacaAnimal values (9  ,'Boxer', 1);
 insert into RacaAnimal values (10 ,'Bulldog', 1);
 insert into RacaAnimal values (11 ,'Bullmastiff', 1);
 insert into RacaAnimal values (12 ,'Bull Terrier', 1);
 insert into RacaAnimal values (13 ,'Chihuahua ', 1);
 insert into RacaAnimal values (14 ,'Chow Chow', 1);
 insert into RacaAnimal values (15 ,'Cocker Americano', 1);
 insert into RacaAnimal values (16 ,'Cocker Ingles', 1);
 insert into RacaAnimal values (17 ,'Collie', 1);
 insert into RacaAnimal values (18 ,'Dalmata', 1);
 insert into RacaAnimal values (19 ,'Dobermann', 1);
 insert into RacaAnimal values (20 ,'Dogue Alemão', 1);
 insert into RacaAnimal values (21 ,'Fila Brasileiro', 1);
 insert into RacaAnimal values (22 ,'Foxhound Ingles', 1);
 insert into RacaAnimal values (23 ,'Fox Terrier', 1);
 insert into RacaAnimal values (24 ,'Golden Retriever', 1);
 insert into RacaAnimal values (25 ,'Husky Siberiano', 1);
 insert into RacaAnimal values (26 ,'Labrador', 1);
 insert into RacaAnimal values (27 ,'Lhasa Apso', 1);
 insert into RacaAnimal values (28 ,'Lulu da Pomerânia ', 1);
 insert into RacaAnimal values (29 ,'Maltês', 1);
 insert into RacaAnimal values (30 ,'Mastiff', 1);
 insert into RacaAnimal values (31 ,'Mastino Napoletano', 1);
 insert into RacaAnimal values (32 ,'Pinscher', 1);
 insert into RacaAnimal values (33 ,'Pointer Ingles', 1);
 insert into RacaAnimal values (34 ,'Poodle', 1);
 insert into RacaAnimal values (35 ,'Rottweiler', 1);
 insert into RacaAnimal values (36 ,'São Bernado', 1);
 insert into RacaAnimal values (37 ,'Schnauzer', 1);
 insert into RacaAnimal values (38 ,'Setter Ingles', 1);
 insert into RacaAnimal values (39 ,'Setter Irlandês', 1);
 insert into RacaAnimal values (40 ,'Shar Pei', 1);
 insert into RacaAnimal values (41 ,'Shih Tzu', 1);
 insert into RacaAnimal values (42 ,'Spitz Alemão', 1);
 insert into RacaAnimal values (43 ,'Staff Bull Terrier', 1);
 insert into RacaAnimal values (44 ,'Teckel', 1);
 insert into RacaAnimal values (45 ,'Terrier Brasileiro', 1);
 insert into RacaAnimal values (46 ,'YorkShire', 1);
 
insert into RacaAnimal values (47  ,'Abissínio', 2);
insert into RacaAnimal values (48  ,'American Shortthair', 2);
insert into RacaAnimal values (49  ,'Angorá', 2);
insert into RacaAnimal values (50  ,'Azul Russo', 2);
insert into RacaAnimal values (51  ,'Bengal', 2);
insert into RacaAnimal values (52  ,'Brazilian Shorthair', 2);
insert into RacaAnimal values (53  ,'British Shorthair', 2);
insert into RacaAnimal values (54  ,'Burmese', 2);
insert into RacaAnimal values (55  ,'Chartreux', 2);
insert into RacaAnimal values (56 ,'Cornish Rex', 2);
insert into RacaAnimal values (57 ,'Devon Rex', 2);
insert into RacaAnimal values (58 ,'Egyptian Mau', 2);
insert into RacaAnimal values (59 ,'European Shorthair', 2);
insert into RacaAnimal values (60 ,'Exótico', 2);
insert into RacaAnimal values (61 ,'Himalaio', 2);
insert into RacaAnimal values (62 ,'Maine Coon', 2);
insert into RacaAnimal values (63 ,'Munchkin', 2);
insert into RacaAnimal values (64 ,'Norwegian Forest', 2);
insert into RacaAnimal values (65 ,'Oriental', 2);
insert into RacaAnimal values (66 ,'Persa', 2);
insert into RacaAnimal values (67 ,'Ragdoll', 2);
insert into RacaAnimal values (68 ,'Sagrado da Birmânia', 2);
insert into RacaAnimal values (69 ,'Savannah', 2);
insert into RacaAnimal values (70 ,'Scottish Fold', 2);
insert into RacaAnimal values (71 ,'Siamês', 2);
insert into RacaAnimal values (72 ,'Sphynx', 2);